import type { Metadata } from "next";
import "./globals.css";
import ContextWrapper from "@/components/ContextWrapper";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ContextWrapper>
          <Navbar />
          <div className="h-[calc(100vh-50px)] flex w-screen z-2 absolute top-[50px]">
            <Sidebar />
            {children}
          </div>
        </ContextWrapper>
      </body>
    </html>
  )
}
