import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContextWrapper from "@/components/ContextWrapper";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <html>
        <body>
          <ContextWrapper>
            <Navbar/>
            <div className="h-[calc(100vh-50px)] w-[100vw] flex z-2 absolute top-[50px]">
              <Sidebar/>
              {children}
            </div>
          </ContextWrapper>
        </body>
      </html>
    )
}
