services:
  postgresdb-dev:
    image: postgres:15
    restart: always
    env_file:
      - .env 
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - mynet

  backend:
    restart: always
    depends_on:
      - redis
      - postgresdb-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "6969:6969"
      - "6970:6970"
    networks:
      - mynet
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_PWD=${PWD}
    env_file:
      - .env
    container_name: expserver-backend
    entrypoint: "/entrypoint.sh --debug=true"
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
       - mynet

networks:
  mynet:
    driver: bridge


volumes:
  redis-dev-data:
  postgres-dev-data: