services:
  postgresdb:
    image: postgres:15
    restart: always
    env_file:
      - .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - mynet

  backend:
    restart: always
    depends_on:
      - redis
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6969:6969"
      - "6970:6970"
    networks:
      - mynet
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_PWD=${PWD}
    env_file:
      - .env.prod
    container_name: expserver-backend
    entrypoint: "/entrypoint.sh --debug=false"
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
       - mynet

networks:
  mynet:
    driver: bridge


volumes:
  redis-data:
  postgres-data: